[workspace]
authors = ["mebbaid <mohamed.elobaid@iit.it>"]
channels = ["conda-forge"]
name = "poly-computations"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
clean = { cmd = "rm -rf build" }
configure = "cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release"
build     = { cmd = "cmake --build build", depends-on = ["configure"] }
test      = { cmd = "ctest --test-dir build --output-on-failure", depends-on = ["build"] }
test-lp  = { cmd = "ctest --test-dir build --output-on-failure -R polycomp_test_lp", depends-on = ["build"] }

cwc = { cmd = "./build/polycomp_test_cwc", depends-on = ["build"] }
bench     = { cmd = "./build/polycomp_bench", depends-on = ["build"] }

[dependencies]
cmake = "*"
cxx-compiler = "*"
ninja = "*"

eigen = "*"
libboost-headers = "*"   
gmp = "*"
highs = ">=1.15.1,<2"
