// Contact wrench cone of a rectangular foot (Caron, Pham, Nakamura, ICRA 2015,
// doi:10.1109/ICRA.2015.7139910), recomputed with polycomp's public API and
// compared with the closed form, row by row.
//
// Foot frame at the centre, half-length X (x), half-width Y (y), normal z.
// Corner forces f_i = (f_ix, f_iy, f_iz) at p_i = (+-X, +-Y, 0), with the
// axis-aligned pyramid  |f_ix| <= mu f_iz,  |f_iy| <= mu f_iz.
// Wrench w = (fx, fy, fz, tx, ty, tz) = sum_i (f_i, p_i x f_i).
//
// Caron's closed form is 16 inequalities U(mu, X, Y) w <= 0. Two checks, one
// per direction of the library:
//
//   (a) H side, "face" form: project(P, 6) of
//         P = { (w, f) in R^18 : w - L f = 0,  16 pyramid rows <= 0 }
//       must return exactly the 16 rows of U, no equalities, and as its
//       generators the origin plus the 16 rays of (b).
//   (b) V side, "span" form (Caron's derivation): the cone generated by the
//       wrenches of the 16 pyramid edges (4 corners x 4 edges),
//         compute_h_representation(from_V(origin, edge wrenches)),
//       must return exactly the 16 rows of U.
//
// "Exactly" means: same set of rows after scaling each to primitive integers
// (positive scaling only), and right-hand sides all zero.

#include <array>
#include <iostream>

#include "polycomp/conversion.hpp"

using namespace polycomp;
using T = Rational;
using C = Integer;

static int failures = 0;
#define CHECK(cond)                                                            \
  do {                                                                         \
    if (!(cond)) {                                                             \
      ++failures;                                                              \
      std::cerr << __FILE__ << ":" << __LINE__ << ": " #cond "\n";             \
    }                                                                          \
  } while (0)

struct Foot { T X, Y, mu; };

// ---------------------------------------------------------------------------
// The data: corner geometry, the corner system, the edge wrenches, Caron's U
// ---------------------------------------------------------------------------

constexpr Eigen::Index NW = 6, NV = NW + 12;  // columns: w (0..5), then f_i at 6 + 3i

struct Corner { T x, y; };
std::array<Corner, 4> corners(const Foot& ft)
{
  return {{{ft.X, ft.Y}, {ft.X, -ft.Y}, {-ft.X, ft.Y}, {-ft.X, -ft.Y}}};
}

// Wrench (f, p x f) of a force f at p = (x, y, 0).
Eigen::Matrix<T, 1, 6> wrench(const Corner& p, const T& fx, const T& fy, const T& fz)
{
  Eigen::Matrix<T, 1, 6> w;
  w << fx, fy, fz, p.y * fz, -p.x * fz, p.x * fy - p.y * fx;
  return w;
}

// P = { (w, f) : w - L f = 0,  pyramid rows <= 0 }  in R^18.
Polyhedron<T> corner_system(const Foot& ft)
{
  RowMat<T> Aeq = RowMat<T>::Zero(NW, NV), A = RowMat<T>::Zero(16, NV);
  Aeq.leftCols(NW).setIdentity();
  const auto P = corners(ft);
  for (int i = 0; i < 4; ++i) {
    const Eigen::Index c = NW + 3 * i;
    // Column c + j of -L is minus the wrench of the unit force e_j at corner i.
    Aeq.col(c + 0) = -wrench(P[i], 1, 0, 0).transpose();
    Aeq.col(c + 1) = -wrench(P[i], 0, 1, 0).transpose();
    Aeq.col(c + 2) = -wrench(P[i], 0, 0, 1).transpose();

    const Eigen::Index r = 4 * i;
    A(r + 0, c + 0) =  1; A(r + 0, c + 2) = -ft.mu;  //  f_ix <= mu f_iz
    A(r + 1, c + 0) = -1; A(r + 1, c + 2) = -ft.mu;  // -f_ix <= mu f_iz
    A(r + 2, c + 1) =  1; A(r + 2, c + 2) = -ft.mu;  //  f_iy <= mu f_iz
    A(r + 3, c + 1) = -1; A(r + 3, c + 2) = -ft.mu;  // -f_iy <= mu f_iz
  }
  return Polyhedron<T>::from_H(A, Vec<T>::Zero(16), Aeq, Vec<T>::Zero(NW));
}

// Wrenches of the pyramid edges (+-mu, +-mu, 1) at the four corners.
RowMat<T> edge_wrenches(const Foot& ft)
{
  RowMat<T> Y(16, NW);
  Eigen::Index k = 0;
  for (const auto& p : corners(ft))
    for (int sx : {1, -1})
      for (int sy : {1, -1}) Y.row(k++) = wrench(p, sx * ft.mu, sy * ft.mu, 1);
  return Y;
}

// Caron's closed form: 16 rows u with u . w <= 0, columns (fx fy fz tx ty tz).
RowMat<T> caron_cwc(const Foot& ft)
{
  const T X = ft.X, Y = ft.Y, mu = ft.mu, s = (X + Y) * mu;
  RowMat<T> U(16, 6);
  U << -1,  0, -mu,   0,   0,  0,
        1,  0, -mu,   0,   0,  0,
        0, -1, -mu,   0,   0,  0,
        0,  1, -mu,   0,   0,  0,
        0,  0,  -Y,  -1,   0,  0,
        0,  0,  -Y,   1,   0,  0,
        0,  0,  -X,   0,  -1,  0,
        0,  0,  -X,   0,   1,  0,
       -Y, -X,  -s,  mu,  mu, -1,
       -Y,  X,  -s,  mu, -mu, -1,
        Y, -X,  -s, -mu,  mu, -1,
        Y,  X,  -s, -mu, -mu, -1,
        Y,  X,  -s,  mu,  mu,  1,
        Y, -X,  -s,  mu, -mu,  1,
       -Y,  X,  -s, -mu,  mu,  1,
       -Y, -X,  -s, -mu, -mu,  1;
  return U;
}

// ---------------------------------------------------------------------------
// Comparison up to positive scaling
// ---------------------------------------------------------------------------

// Each row scaled to primitive integers (positive factor only).
RowMat<C> canonical(const RowMat<T>& M)
{
  RowMat<C> K(M.rows(), M.cols());
  for (Eigen::Index i = 0; i < M.rows(); ++i) {
    Eigen::Matrix<T, 1, Eigen::Dynamic> r = M.row(i);
    internal::lift(r(0), r.tail(r.size() - 1), K.row(i));
  }
  return K;
}

// Same number of rows and every row of A is a row of B (rows distinct).
bool same_rows(const RowMat<T>& A, const RowMat<T>& B)
{
  const RowMat<C> a = canonical(A), b = canonical(B);
  if (a.rows() != b.rows() || internal::unique_rows(a).rows() != a.rows()) return false;
  for (Eigen::Index i = 0; i < a.rows(); ++i) {
    bool found = false;
    for (Eigen::Index j = 0; j < b.rows() && !found; ++j) found = a.row(i) == b.row(j);
    if (!found) return false;
  }
  return true;
}

// ---------------------------------------------------------------------------

void run_foot(const Foot& ft)
{
  std::cout << "--- foot X=" << ft.X << " Y=" << ft.Y << " mu=" << ft.mu << " ---\n";
  const RowMat<T> U = caron_cwc(ft), Y = edge_wrenches(ft);

  // (a) H side: project the 18-dimensional corner system onto w.
  std::vector<Eigen::Index> trace;
  const auto P = project(corner_system(ft), NW, &trace);
  CHECK(P.h->A_eq.rows() == 0);
  CHECK(P.h->z.isZero());
  CHECK(same_rows(P.h->A, U));
  // ... and its generators: the apex and the 16 edge wrenches, all extreme.
  CHECK(P.v->V.rows() == 1 && P.v->V.isZero());
  CHECK(P.v->L.rows() == 0);
  CHECK(same_rows(P.v->Y, Y));

  std::cout << "(a) project, R^18 -> R^6: trace";
  for (auto x : trace) std::cout << ' ' << x;
  std::cout << " -> " << P.h->A.rows() << " facets, " << P.v->Y.rows() << " extreme rays\n";

  // (b) V side: the cone over the edge wrenches.
  auto Q = Polyhedron<T>::from_V(RowMat<T>::Zero(1, NW), Y);
  trace.clear();
  compute_h_representation(Q, &trace);
  CHECK(Q.h->A_eq.rows() == 0);
  CHECK(Q.h->z.isZero());
  CHECK(same_rows(Q.h->A, U));

  std::cout << "(b) cone over edge wrenches: trace";
  for (auto x : trace) std::cout << ' ' << x;
  std::cout << " -> " << Q.h->A.rows() << " facets\n";
}

int main()
{
  run_foot({T(2), T(1), T(1, 2)});      // the running example
  run_foot({T(1), T(1), T(1)});         // square foot, mu = 1
  run_foot({T(3), T(1, 2), T(7, 10)});  // elongated foot, mu = 0.7
  std::cout << (failures ? "FAILED\n" : "all tests passed\n");
  return failures != 0;
}